TDV.PlayerAPI.defineScript({ "definitions": [
 {
  "partial": false,
  "hfov": 360,
  "vfov": 180,
  "hfovMax": 120,
  "label": "1114",
  "class": "Panorama",
  "thumbnailUrl": "media/panorama_CE9DC9EB_C487_4099_41A7_7D29A943B8FA_t.jpg",
  "hfovMin": 60,
  "id": "panorama_CE9DC9EB_C487_4099_41A7_7D29A943B8FA",
  "frames": [
   {
    "stereoSphere": {
     "levels": [
      {
       "height": 6434,
       "width": 6434,
       "url": "media/panorama_CE9DC9EB_C487_4099_41A7_7D29A943B8FA_hq.jpeg",
       "class": "ImageResourceLevel"
      },
      {
       "height": 3217,
       "width": 3217,
       "url": "media/panorama_CE9DC9EB_C487_4099_41A7_7D29A943B8FA.jpeg",
       "class": "ImageResourceLevel"
      }
     ],
     "class": "ImageResource"
    },
    "overlays": [
     {
      "useHandCursor": true,
      "areas": [
       {
        "mapColor": "#FF0000",
        "rollOver": "this.showPopupMedia(this.window_D8430452_CC9F_478B_41E1_4E682E8F29DA, this.video_CA47200C_C486_DF9F_41C1_6896EBE88367, this.playList_D8285FDE_CC9F_40BB_41DD_F8C4D1F936EE, '90%', '90%', false, true); this.playList_D8285FDE_CC9F_40BB_41DD_F8C4D1F936EE.set('selectedIndex', 0); ; this.viewer_uidD82F9FDE_CC9F_40BB_41E2_56F6932334F2VideoPlayer.play(); ; this.pauseGlobalAudios()",
        "class": "HotspotPanoramaOverlayArea"
       }
      ],
      "id": "overlay_D8ADADBC_CC99_40FF_41E2_3A537B89CFDF",
      "items": [
       {
        "hfov": 12.57,
        "yaw": -167.29,
        "class": "HotspotPanoramaOverlayImage",
        "roll": 0,
        "image": {
         "levels": [
          {
           "height": 130,
           "width": 225,
           "url": "media/panorama_CE9DC9EB_C487_4099_41A7_7D29A943B8FA_0_HS_1_0.png",
           "class": "ImageResourceLevel"
          }
         ],
         "class": "ImageResource"
        },
        "pitch": -6.22
       }
      ],
      "maps": [
       {
        "hfov": 12.57,
        "yaw": -167.29,
        "image": {
         "levels": [
          {
           "height": 65,
           "width": 112,
           "url": "media/panorama_CE9DC9EB_C487_4099_41A7_7D29A943B8FA_0_HS_1_1_0_map.gif",
           "class": "ImageResourceLevel"
          }
         ],
         "class": "ImageResource"
        },
        "class": "HotspotPanoramaOverlayMap",
        "pitch": -6.22
       }
      ],
      "class": "HotspotPanoramaOverlay",
      "rollOverDisplay": true
     }
    ],
    "class": "SphericPanoramaFrame",
    "thumbnailUrl": "media/panorama_CE9DC9EB_C487_4099_41A7_7D29A943B8FA_t.jpg"
   }
  ],
  "pitch": 0
 },
 {
  "buttonRestart": {
   "mode": "push",
   "width": 40,
   "height": 40,
   "iconURL": "skin/IconButton_52344940_5F01_EFC4_41BB_2A5E51966695.png",
   "minHeight": 0,
   "borderRadius": 0,
   "horizontalAlign": "center",
   "shadow": false,
   "transparencyActive": true,
   "cursor": "hand",
   "paddingRight": 0,
   "backgroundOpacity": 0,
   "class": "IconButton",
   "paddingBottom": 0,
   "pressedIconURL": "skin/IconButton_52344940_5F01_EFC4_41BB_2A5E51966695_pressed.png",
   "id": "IconButton_52344940_5F01_EFC4_41BB_2A5E51966695",
   "paddingLeft": 0,
   "borderSize": 0,
   "minWidth": 0,
   "verticalAlign": "middle",
   "rollOverIconURL": "skin/IconButton_52344940_5F01_EFC4_41BB_2A5E51966695_rollover.png",
   "paddingTop": 0
  },
  "displayPlaybackBar": true,
  "gyroscopeVerticalDraggingEnabled": true,
  "mouseControlMode": "drag_acceleration",
  "buttonMoveRight": {
   "mode": "push",
   "width": 40,
   "height": 40,
   "iconURL": "skin/IconButton_52344940_5F01_EFC4_4184_BD88B8F3E7CC.png",
   "minHeight": 0,
   "borderRadius": 0,
   "horizontalAlign": "center",
   "shadow": false,
   "transparencyActive": true,
   "cursor": "hand",
   "paddingRight": 0,
   "backgroundOpacity": 0,
   "class": "IconButton",
   "paddingBottom": 0,
   "pressedIconURL": "skin/IconButton_52344940_5F01_EFC4_4184_BD88B8F3E7CC_pressed.png",
   "id": "IconButton_52344940_5F01_EFC4_4184_BD88B8F3E7CC",
   "paddingLeft": 0,
   "borderSize": 0,
   "minWidth": 0,
   "verticalAlign": "middle",
   "rollOverIconURL": "skin/IconButton_52344940_5F01_EFC4_4184_BD88B8F3E7CC_rollover.png",
   "paddingTop": 0
  },
  "buttonCardboardView": {
   "maxHeight": 70,
   "width": 70,
   "height": 70,
   "iconURL": "skin/IconButton_C8BB337C_C487_407F_41C6_55C7E5D3FD2F.png",
   "minHeight": 1,
   "borderRadius": 0,
   "horizontalAlign": "center",
   "mode": "push",
   "shadow": false,
   "transparencyActive": false,
   "cursor": "hand",
   "paddingRight": 0,
   "backgroundOpacity": 0,
   "class": "IconButton",
   "paddingBottom": 0,
   "id": "IconButton_C8BB337C_C487_407F_41C6_55C7E5D3FD2F",
   "paddingLeft": 0,
   "maxWidth": 70,
   "borderSize": 0,
   "minWidth": 1,
   "paddingTop": 0,
   "verticalAlign": "middle"
  },
  "buttonMoveDown": {
   "mode": "push",
   "width": 40,
   "height": 40,
   "iconURL": "skin/IconButton_52344940_5F01_EFC4_41B5_303051AFBE15.png",
   "minHeight": 0,
   "borderRadius": 0,
   "horizontalAlign": "center",
   "shadow": false,
   "transparencyActive": true,
   "cursor": "hand",
   "paddingRight": 0,
   "backgroundOpacity": 0,
   "class": "IconButton",
   "paddingBottom": 0,
   "pressedIconURL": "skin/IconButton_52344940_5F01_EFC4_41B5_303051AFBE15_pressed.png",
   "id": "IconButton_52344940_5F01_EFC4_41B5_303051AFBE15",
   "paddingLeft": 0,
   "borderSize": 0,
   "minWidth": 0,
   "verticalAlign": "middle",
   "rollOverIconURL": "skin/IconButton_52344940_5F01_EFC4_41B5_303051AFBE15_rollover.png",
   "paddingTop": 0
  },
  "viewerArea": "this.MainViewer",
  "buttonPlayLeft": {
   "mode": "push",
   "width": 40,
   "height": 40,
   "iconURL": "skin/IconButton_52344940_5F01_EFC4_41D4_A1CCD7021F0A.png",
   "minHeight": 0,
   "borderRadius": 0,
   "horizontalAlign": "center",
   "shadow": false,
   "transparencyActive": true,
   "cursor": "hand",
   "paddingRight": 0,
   "backgroundOpacity": 0,
   "class": "IconButton",
   "paddingBottom": 0,
   "pressedIconURL": "skin/IconButton_52344940_5F01_EFC4_41D4_A1CCD7021F0A_pressed.png",
   "id": "IconButton_52344940_5F01_EFC4_41D4_A1CCD7021F0A",
   "paddingLeft": 0,
   "borderSize": 0,
   "minWidth": 0,
   "verticalAlign": "middle",
   "rollOverIconURL": "skin/IconButton_52344940_5F01_EFC4_41D4_A1CCD7021F0A_rollover.png",
   "paddingTop": 0
  },
  "class": "PanoramaPlayer",
  "buttonMoveLeft": {
   "mode": "push",
   "width": 40,
   "height": 40,
   "iconURL": "skin/IconButton_52344940_5F01_EFC4_41D0_C6DE67446A2C.png",
   "minHeight": 0,
   "borderRadius": 0,
   "horizontalAlign": "center",
   "shadow": false,
   "transparencyActive": true,
   "cursor": "hand",
   "paddingRight": 0,
   "backgroundOpacity": 0,
   "class": "IconButton",
   "paddingBottom": 0,
   "pressedIconURL": "skin/IconButton_52344940_5F01_EFC4_41D0_C6DE67446A2C_pressed.png",
   "id": "IconButton_52344940_5F01_EFC4_41D0_C6DE67446A2C",
   "paddingLeft": 0,
   "borderSize": 0,
   "minWidth": 0,
   "verticalAlign": "middle",
   "rollOverIconURL": "skin/IconButton_52344940_5F01_EFC4_41D0_C6DE67446A2C_rollover.png",
   "paddingTop": 0
  },
  "buttonPause": {
   "mode": "toggle",
   "width": 40,
   "height": 40,
   "iconURL": "skin/IconButton_52344940_5F01_EFC4_41CC_4A5BFB01C469.png",
   "minHeight": 0,
   "borderRadius": 0,
   "horizontalAlign": "center",
   "shadow": false,
   "transparencyActive": true,
   "cursor": "hand",
   "paddingRight": 0,
   "backgroundOpacity": 0,
   "class": "IconButton",
   "paddingBottom": 0,
   "pressedIconURL": "skin/IconButton_52344940_5F01_EFC4_41CC_4A5BFB01C469_pressed.png",
   "id": "IconButton_52344940_5F01_EFC4_41CC_4A5BFB01C469",
   "paddingLeft": 0,
   "borderSize": 0,
   "minWidth": 0,
   "verticalAlign": "middle",
   "paddingTop": 0
  },
  "id": "MainViewerPanoramaPlayer",
  "buttonZoomOut": {
   "mode": "push",
   "width": 40,
   "height": 40,
   "iconURL": "skin/IconButton_52344940_5F01_EFC4_41D7_BE81DEFE8744.png",
   "minHeight": 0,
   "borderRadius": 0,
   "horizontalAlign": "center",
   "shadow": false,
   "transparencyActive": true,
   "cursor": "hand",
   "paddingRight": 0,
   "backgroundOpacity": 0,
   "class": "IconButton",
   "paddingBottom": 0,
   "pressedIconURL": "skin/IconButton_52344940_5F01_EFC4_41D7_BE81DEFE8744_pressed.png",
   "id": "IconButton_52344940_5F01_EFC4_41D7_BE81DEFE8744",
   "paddingLeft": 0,
   "borderSize": 0,
   "minWidth": 0,
   "verticalAlign": "middle",
   "rollOverIconURL": "skin/IconButton_52344940_5F01_EFC4_41D7_BE81DEFE8744_rollover.png",
   "paddingTop": 0
  },
  "buttonZoomIn": {
   "mode": "push",
   "width": 40,
   "height": 40,
   "iconURL": "skin/IconButton_52344940_5F01_EFC4_41BB_7EDA152A8375.png",
   "minHeight": 0,
   "borderRadius": 0,
   "horizontalAlign": "center",
   "shadow": false,
   "transparencyActive": true,
   "cursor": "hand",
   "paddingRight": 0,
   "backgroundOpacity": 0,
   "class": "IconButton",
   "paddingBottom": 0,
   "pressedIconURL": "skin/IconButton_52344940_5F01_EFC4_41BB_7EDA152A8375_pressed.png",
   "id": "IconButton_52344940_5F01_EFC4_41BB_7EDA152A8375",
   "paddingLeft": 0,
   "borderSize": 0,
   "minWidth": 0,
   "verticalAlign": "middle",
   "rollOverIconURL": "skin/IconButton_52344940_5F01_EFC4_41BB_7EDA152A8375_rollover.png",
   "paddingTop": 0
  },
  "buttonMoveUp": {
   "mode": "push",
   "width": 40,
   "height": 40,
   "iconURL": "skin/IconButton_52344940_5F01_EFC4_41B6_26FA0557CEC9.png",
   "minHeight": 0,
   "borderRadius": 0,
   "horizontalAlign": "center",
   "shadow": false,
   "transparencyActive": true,
   "cursor": "hand",
   "paddingRight": 0,
   "backgroundOpacity": 0,
   "class": "IconButton",
   "paddingBottom": 0,
   "pressedIconURL": "skin/IconButton_52344940_5F01_EFC4_41B6_26FA0557CEC9_pressed.png",
   "id": "IconButton_52344940_5F01_EFC4_41B6_26FA0557CEC9",
   "paddingLeft": 0,
   "borderSize": 0,
   "minWidth": 0,
   "verticalAlign": "middle",
   "rollOverIconURL": "skin/IconButton_52344940_5F01_EFC4_41B6_26FA0557CEC9_rollover.png",
   "paddingTop": 0
  },
  "buttonPlayRight": {
   "mode": "push",
   "width": 40,
   "height": 40,
   "iconURL": "skin/IconButton_52344940_5F01_EFC4_41C7_7571D1A24A33.png",
   "minHeight": 0,
   "borderRadius": 0,
   "horizontalAlign": "center",
   "shadow": false,
   "transparencyActive": true,
   "cursor": "hand",
   "paddingRight": 0,
   "backgroundOpacity": 0,
   "class": "IconButton",
   "paddingBottom": 0,
   "pressedIconURL": "skin/IconButton_52344940_5F01_EFC4_41C7_7571D1A24A33_pressed.png",
   "id": "IconButton_52344940_5F01_EFC4_41C7_7571D1A24A33",
   "paddingLeft": 0,
   "borderSize": 0,
   "minWidth": 0,
   "verticalAlign": "middle",
   "rollOverIconURL": "skin/IconButton_52344940_5F01_EFC4_41C7_7571D1A24A33_rollover.png",
   "paddingTop": 0
  },
  "preloadEnabled": false,
  "touchControlMode": "drag_rotation"
 },
 {
  "initialPosition": {
   "yaw": 0,
   "class": "PanoramaCameraPosition",
   "pitch": 0
  },
  "id": "panorama_CE9DC9EB_C487_4099_41A7_7D29A943B8FA_camera",
  "automaticZoomSpeed": 10,
  "initialSequence": {
   "movements": [
    {
     "yawDelta": 18.5,
     "yawSpeed": 7.96,
     "class": "DistancePanoramaCameraMovement",
     "easing": "cubic_in"
    },
    {
     "yawDelta": 323,
     "yawSpeed": 7.96,
     "class": "DistancePanoramaCameraMovement",
     "easing": "linear"
    },
    {
     "yawDelta": 18.5,
     "yawSpeed": 7.96,
     "class": "DistancePanoramaCameraMovement",
     "easing": "cubic_out"
    }
   ],
   "class": "PanoramaCameraSequence",
   "restartMovementOnUserInteraction": false
  },
  "class": "PanoramaCamera"
 },
 {
  "label": "Love_songs_for_WhatsApp_Status_1_minute",
  "class": "Video",
  "video": {
   "mp4Url": "media/video_CA47200C_C486_DF9F_41C1_6896EBE88367.mp4",
   "height": 360,
   "width": 636,
   "class": "VideoResource"
  },
  "width": 636,
  "id": "video_CA47200C_C486_DF9F_41C1_6896EBE88367",
  "loop": false,
  "thumbnailUrl": "media/video_CA47200C_C486_DF9F_41C1_6896EBE88367_t.jpg",
  "height": 360,
  "scaleMode": "fit_inside"
 },
 {
  "buttonRestart": "this.IconButton_52344940_5F01_EFC4_41BB_2A5E51966695",
  "buttonPause": "this.IconButton_52344940_5F01_EFC4_41CC_4A5BFB01C469",
  "id": "MainViewerVideoPlayer",
  "displayPlaybackBar": true,
  "viewerArea": "this.MainViewer",
  "class": "VideoPlayer"
 },
 {
  "id": "mainPlayList",
  "class": "PlayList",
  "items": [
   {
    "begin": "this.setEndToItemIndex(this.mainPlayList, 0, 1)",
    "media": "this.panorama_CE9DC9EB_C487_4099_41A7_7D29A943B8FA",
    "camera": "this.panorama_CE9DC9EB_C487_4099_41A7_7D29A943B8FA_camera",
    "player": "this.MainViewerPanoramaPlayer",
    "class": "PanoramaPlayListItem"
   },
   {
    "player": "this.MainViewerVideoPlayer",
    "media": "this.video_CA47200C_C486_DF9F_41C1_6896EBE88367",
    "begin": "this.fixTogglePlayPauseButton(this.MainViewerVideoPlayer); this.setEndToItemIndex(this.mainPlayList, 1, 0)",
    "class": "VideoPlayListItem",
    "start": "this.MainViewerVideoPlayer.set('displayPlaybackBar', true); this.changeBackgroundWhilePlay(this.mainPlayList, 1, '#000000'); this.pauseGlobalAudiosWhilePlayItem(this.mainPlayList, 1, this.video_CA47200C_C486_DF9F_41C1_6896EBE88367)"
   }
  ]
 },
 {
  "id": "playList_D8285FDE_CC9F_40BB_41DD_F8C4D1F936EE",
  "class": "PlayList",
  "items": [
   {
    "begin": "this.fixTogglePlayPauseButton(this.viewer_uidD82F9FDE_CC9F_40BB_41E2_56F6932334F2VideoPlayer)",
    "media": "this.video_CA47200C_C486_DF9F_41C1_6896EBE88367",
    "player": {
     "buttonRestart": "this.IconButton_52344940_5F01_EFC4_41BB_2A5E51966695",
     "buttonPause": "this.IconButton_52344940_5F01_EFC4_41CC_4A5BFB01C469",
     "id": "viewer_uidD82F9FDE_CC9F_40BB_41E2_56F6932334F2VideoPlayer",
     "displayPlaybackBar": true,
     "viewerArea": {
      "playbackBarOpacity": 1,
      "playbackBarProgressOpacity": 1,
      "toolTipBorderColor": "#767676",
      "playbackBarHeadBorderColor": "#000000",
      "playbackBarHeadShadowBlurRadius": 3,
      "toolTipPaddingLeft": 6,
      "playbackBarHeadShadowHorizontalLength": 0,
      "paddingTop": 0,
      "toolTipShadowOpacity": 1,
      "playbackBarHeadHeight": 30,
      "playbackBarBorderSize": 2,
      "toolTipTextShadowBlurRadius": 3,
      "borderRadius": 0,
      "playbackBarLeft": 0,
      "playbackBarHeadBackgroundColorRatios": [
       0,
       1
      ],
      "toolTipTextShadowColor": "#000000",
      "shadow": false,
      "progressBarBackgroundColorRatios": [
       0,
       1
      ],
      "progressBarBorderColor": "#000000",
      "playbackBarHeadShadowColor": "#000000",
      "toolTipBorderSize": 1,
      "progressBackgroundColorDirection": "vertical",
      "playbackBarBackgroundOpacity": 1,
      "toolTipFontFamily": "Arial",
      "progressBarOpacity": 1,
      "paddingLeft": 0,
      "progressBorderColor": "#AAAAAA",
      "playbackBarBottom": 0,
      "progressBarBackgroundColor": [
       "#222222",
       "#444444"
      ],
      "playbackBarHeadOpacity": 1,
      "progressBottom": 2,
      "playbackBarHeadShadowVerticalLength": 0,
      "toolTipPaddingBottom": 4,
      "minWidth": 100,
      "borderSize": 0,
      "progressBackgroundOpacity": 1,
      "progressOpacity": 1,
      "playbackBarProgressBackgroundColorDirection": "vertical",
      "toolTipBackgroundColor": "#F6F6F6",
      "toolTipTextShadowOpacity": 0,
      "progressBorderRadius": 4,
      "progressBackgroundColor": [
       "#EEEEEE",
       "#CCCCCC"
      ],
      "playbackBarBackgroundColor": [
       "#EEEEEE",
       "#CCCCCC"
      ],
      "progressBorderSize": 2,
      "playbackBarHeight": 20,
      "toolTipOpacity": 1,
      "playbackBarHeadBackgroundColorDirection": "vertical",
      "playbackBarProgressBorderSize": 0,
      "playbackBarHeadWidth": 6,
      "playbackBarProgressBackgroundColor": [
       "#222222",
       "#444444"
      ],
      "playbackBarBackgroundColorDirection": "vertical",
      "width": "100%",
      "minHeight": 50,
      "progressBarBackgroundColorDirection": "vertical",
      "progressBarBorderRadius": 4,
      "progressBarBorderSize": 0,
      "playbackBarRight": 0,
      "toolTipPaddingTop": 4,
      "playbackBarProgressBorderRadius": 0,
      "height": "100%",
      "transitionMode": "blending",
      "playbackBarBorderColor": "#AAAAAA",
      "toolTipShadowColor": "#333333",
      "toolTipShadowBlurRadius": 3,
      "toolTipShadowSpread": 0,
      "playbackBarHeadShadow": true,
      "toolTipFontSize": 12,
      "paddingRight": 0,
      "toolTipFontColor": "#606060",
      "paddingBottom": 0,
      "toolTipFontStyle": "normal",
      "class": "ViewerArea",
      "playbackBarBorderRadius": 4,
      "toolTipBorderRadius": 3,
      "toolTipShadowVerticalLength": 0,
      "toolTipFontWeight": "normal",
      "playbackBarHeadBackgroundColor": [
       "#111111",
       "#666666"
      ],
      "playbackBarProgressBorderColor": "#000000",
      "id": "viewer_uidD9849760_CC8B_C188_41CA_880AF429001D",
      "progressRight": 10,
      "playbackBarHeadShadowOpacity": 0.7,
      "toolTipPaddingRight": 6,
      "toolTipShadowHorizontalLength": 0,
      "playbackBarHeadBorderRadius": 0,
      "progressHeight": 20,
      "playbackBarProgressBackgroundColorRatios": [
       0,
       1
      ],
      "progressLeft": 10,
      "progressBackgroundColorRatios": [
       0,
       1
      ],
      "playbackBarHeadBorderSize": 0
     },
     "class": "VideoPlayer"
    },
    "class": "VideoPlayListItem",
    "start": "this.viewer_uidD82F9FDE_CC9F_40BB_41E2_56F6932334F2VideoPlayer.set('displayPlaybackBar', true); this.changeBackgroundWhilePlay(this.playList_D8285FDE_CC9F_40BB_41DD_F8C4D1F936EE, 0, '#000000'); this.pauseGlobalAudiosWhilePlayItem(this.playList_D8285FDE_CC9F_40BB_41DD_F8C4D1F936EE, 0, this.video_CA47200C_C486_DF9F_41C1_6896EBE88367)"
   }
  ]
 },
 {
  "backgroundColor": [],
  "titlePaddingLeft": 5,
  "closeButtonPressedBackgroundColor": [],
  "titleFontFamily": "Arial",
  "modal": true,
  "closeButtonIconHeight": 20,
  "headerBorderSize": 0,
  "borderRadius": 5,
  "titlePaddingRight": 5,
  "bodyPaddingRight": 0,
  "bodyBackgroundColor": [
   "#FFFFFF",
   "#DDDDDD",
   "#FFFFFF"
  ],
  "title": "",
  "footerBackgroundColorDirection": "vertical",
  "titleFontColor": "#000000",
  "shadow": true,
  "veilOpacity": 0.4,
  "titleFontWeight": "normal",
  "titleTextDecoration": "none",
  "titlePaddingBottom": 5,
  "veilColor": [
   "#000000",
   "#000000"
  ],
  "titlePaddingTop": 5,
  "closeButtonBackgroundColor": [],
  "backgroundOpacity": 1,
  "titleFontSize": 14,
  "paddingLeft": 0,
  "footerHeight": 5,
  "overflow": "scroll",
  "closeButtonPressedIconColor": "#FFFFFF",
  "headerVerticalAlign": "middle",
  "closeButtonRollOverBackgroundColor": [],
  "closeButtonIconLineWidth": 2,
  "minWidth": 20,
  "shadowColor": "#000000",
  "backgroundColorDirection": "vertical",
  "headerBorderColor": "#000000",
  "closeButtonIconColor": "#B2B2B2",
  "borderSize": 0,
  "headerBackgroundColorRatios": [
   0,
   0.1,
   1
  ],
  "closeButtonIconWidth": 20,
  "closeButtonBackgroundColorRatios": [],
  "bodyBackgroundOpacity": 0,
  "scrollBarWidth": 10,
  "children": [
   "this.viewer_uidD9849760_CC8B_C188_41CA_880AF429001D"
  ],
  "scrollBarMargin": 2,
  "closeButtonRollOverIconColor": "#FFFFFF",
  "bodyPaddingBottom": 0,
  "verticalAlign": "middle",
  "closeButtonPressedBackgroundColorRatios": [
   0
  ],
  "veilColorRatios": [
   0,
   1
  ],
  "closeButtonPressedIconLineWidth": 3,
  "headerBackgroundOpacity": 0,
  "bodyBackgroundColorRatios": [
   0,
   0.5,
   1
  ],
  "shadowHorizontalLength": 3,
  "backgroundColorRatios": [],
  "veilColorDirection": "horizontal",
  "bodyBackgroundColorDirection": "vertical",
  "minHeight": 20,
  "closeButtonBorderRadius": 11,
  "shadowOpacity": 0.5,
  "closeButtonRollOverBackgroundColorRatios": [
   0
  ],
  "headerPaddingTop": 10,
  "veilHideEffect": {
   "duration": 500,
   "class": "FadeOutEffect",
   "easing": "cubic_in_out"
  },
  "showEffect": {
   "duration": 500,
   "class": "FadeInEffect",
   "easing": "cubic_in_out"
  },
  "hideEffect": {
   "duration": 500,
   "class": "FadeOutEffect",
   "easing": "cubic_in_out"
  },
  "bodyPaddingTop": 0,
  "headerBackgroundColorDirection": "vertical",
  "footerBackgroundOpacity": 0,
  "gap": 10,
  "bodyPaddingLeft": 0,
  "shadowSpread": 1,
  "horizontalAlign": "center",
  "footerBackgroundColorRatios": [
   0,
   0.9,
   1
  ],
  "paddingRight": 0,
  "contentOpaque": false,
  "titleFontStyle": "normal",
  "scrollBarColor": "#000000",
  "paddingBottom": 0,
  "scrollBarVisible": "rollOver",
  "class": "Window",
  "shadowBlurRadius": 6,
  "veilShowEffect": {
   "duration": 500,
   "class": "FadeInEffect",
   "easing": "cubic_in_out"
  },
  "scrollBarOpacity": 0.5,
  "headerPaddingLeft": 10,
  "id": "window_D8430452_CC9F_478B_41E1_4E682E8F29DA",
  "headerBackgroundColor": [
   "#DDDDDD",
   "#EEEEEE",
   "#FFFFFF"
  ],
  "shadowVerticalLength": 0,
  "layout": "vertical",
  "footerBackgroundColor": [
   "#FFFFFF",
   "#EEEEEE",
   "#DDDDDD"
  ],
  "headerPaddingRight": 0,
  "close": "this.playList_D8285FDE_CC9F_40BB_41DD_F8C4D1F936EE.set('selectedIndex', -1);; this.resumeGlobalAudios()",
  "headerPaddingBottom": 5,
  "paddingTop": 0
 }
], "children": [
 {
  "playbackBarOpacity": 1,
  "playbackBarProgressOpacity": 1,
  "toolTipBorderColor": "#767676",
  "playbackBarHeadBorderColor": "#000000",
  "playbackBarHeadShadowBlurRadius": 3,
  "toolTipPaddingLeft": 6,
  "playbackBarHeadShadowHorizontalLength": 0,
  "paddingTop": 0,
  "toolTipShadowOpacity": 1,
  "playbackBarHeadHeight": 30,
  "playbackBarBorderSize": 2,
  "borderRadius": 0,
  "playbackBarLeft": 0,
  "toolTipTextShadowBlurRadius": 3,
  "playbackBarHeadBackgroundColorRatios": [
   0,
   1
  ],
  "toolTipTextShadowColor": "#000000",
  "shadow": false,
  "progressBarBackgroundColorRatios": [
   0,
   1
  ],
  "progressBarBorderColor": "#000000",
  "playbackBarHeadShadowColor": "#000000",
  "toolTipBorderSize": 1,
  "progressBackgroundColorDirection": "vertical",
  "playbackBarBackgroundOpacity": 1,
  "toolTipFontFamily": "Arial",
  "progressBarOpacity": 1,
  "paddingLeft": 0,
  "progressBorderColor": "#AAAAAA",
  "playbackBarBottom": 10,
  "progressBarBackgroundColor": [
   "#222222",
   "#444444"
  ],
  "playbackBarHeadOpacity": 1,
  "progressBottom": 1,
  "playbackBarHeadShadowVerticalLength": 0,
  "toolTipPaddingBottom": 4,
  "minWidth": 100,
  "borderSize": 0,
  "progressBackgroundOpacity": 1,
  "progressOpacity": 1,
  "playbackBarProgressBackgroundColorDirection": "vertical",
  "toolTipBackgroundColor": "#F6F6F6",
  "toolTipTextShadowOpacity": 0,
  "progressBorderRadius": 4,
  "progressBackgroundColor": [
   "#EEEEEE",
   "#CCCCCC"
  ],
  "playbackBarBackgroundColor": [
   "#EEEEEE",
   "#CCCCCC"
  ],
  "progressBorderSize": 2,
  "playbackBarHeight": 20,
  "toolTipOpacity": 1,
  "playbackBarHeadBackgroundColorDirection": "vertical",
  "playbackBarProgressBorderSize": 0,
  "playbackBarHeadWidth": 6,
  "playbackBarProgressBackgroundColor": [
   "#222222",
   "#444444"
  ],
  "playbackBarBackgroundColorDirection": "vertical",
  "width": "100%",
  "minHeight": 50,
  "progressBarBackgroundColorDirection": "vertical",
  "progressBarBorderRadius": 4,
  "progressBarBorderSize": 0,
  "playbackBarRight": 0,
  "toolTipPaddingTop": 4,
  "playbackBarProgressBorderRadius": 0,
  "height": "100%",
  "toolTipShadowSpread": 0,
  "playbackBarBorderColor": "#AAAAAA",
  "toolTipShadowColor": "#333333",
  "toolTipShadowBlurRadius": 3,
  "transitionMode": "blending",
  "playbackBarHeadShadow": true,
  "toolTipFontSize": 12,
  "paddingRight": 0,
  "toolTipFontColor": "#606060",
  "top": 0,
  "paddingBottom": 0,
  "toolTipFontStyle": "normal",
  "class": "ViewerArea",
  "playbackBarBorderRadius": 4,
  "toolTipBorderRadius": 3,
  "toolTipShadowVerticalLength": 0,
  "toolTipFontWeight": "normal",
  "playbackBarHeadBackgroundColor": [
   "#111111",
   "#666666"
  ],
  "playbackBarProgressBorderColor": "#000000",
  "id": "MainViewer",
  "progressRight": 10,
  "playbackBarHeadShadowOpacity": 0.7,
  "toolTipPaddingRight": 6,
  "toolTipShadowHorizontalLength": 0,
  "left": 0,
  "playbackBarHeadBorderRadius": 0,
  "progressHeight": 20,
  "playbackBarProgressBackgroundColorRatios": [
   0,
   1
  ],
  "progressLeft": 10,
  "progressBackgroundColorRatios": [
   0,
   1
  ],
  "playbackBarHeadBorderSize": 0
 },
 {
  "verticalAlign": "middle",
  "width": "100%",
  "height": 142,
  "minHeight": 1,
  "gap": 10,
  "borderRadius": 0,
  "horizontalAlign": "center",
  "shadow": false,
  "layout": "horizontal",
  "scrollBarOpacity": 0.5,
  "contentOpaque": false,
  "scrollBarColor": "#000000",
  "paddingRight": 0,
  "backgroundOpacity": 0,
  "class": "Container",
  "paddingBottom": 0,
  "bottom": "0%",
  "overflow": "scroll",
  "paddingLeft": 0,
  "borderSize": 0,
  "minWidth": 1,
  "left": "0%",
  "scrollBarWidth": 10,
  "scrollBarVisible": "rollOver",
  "children": [
   {
    "width": 421,
    "height": "100%",
    "minHeight": 20,
    "borderRadius": 0,
    "gap": 4,
    "horizontalAlign": "center",
    "shadow": false,
    "layout": "horizontal",
    "scrollBarOpacity": 0.5,
    "contentOpaque": false,
    "scrollBarColor": "#000000",
    "paddingRight": 0,
    "backgroundOpacity": 0,
    "class": "Container",
    "paddingLeft": 0,
    "id": "Container_52344940_5F01_EFC4_41D4_ABA40101D8BF",
    "overflow": "hidden",
    "paddingBottom": 0,
    "borderSize": 0,
    "minWidth": 421,
    "scrollBarWidth": 10,
    "scrollBarVisible": "rollOver",
    "children": [
     "this.IconButton_52344940_5F01_EFC4_41D7_BE81DEFE8744",
     "this.IconButton_52344940_5F01_EFC4_41BB_2A5E51966695",
     "this.IconButton_52344940_5F01_EFC4_41D4_A1CCD7021F0A",
     "this.IconButton_52344940_5F01_EFC4_41D0_C6DE67446A2C",
     {
      "width": 40,
      "height": "100%",
      "minHeight": 20,
      "borderRadius": 0,
      "gap": 4,
      "horizontalAlign": "center",
      "shadow": false,
      "layout": "vertical",
      "scrollBarOpacity": 0.5,
      "contentOpaque": false,
      "scrollBarColor": "#000000",
      "scrollBarVisible": "rollOver",
      "backgroundOpacity": 0,
      "class": "Container",
      "paddingLeft": 0,
      "id": "Container_52344940_5F01_EFC4_41D6_7E3303CC9C74",
      "overflow": "hidden",
      "paddingBottom": 0,
      "borderSize": 0,
      "minWidth": 20,
      "scrollBarWidth": 10,
      "paddingRight": 0,
      "children": [
       "this.IconButton_52344940_5F01_EFC4_41B6_26FA0557CEC9",
       "this.IconButton_52344940_5F01_EFC4_41CC_4A5BFB01C469",
       "this.IconButton_52344940_5F01_EFC4_41B5_303051AFBE15"
      ],
      "paddingTop": 0,
      "verticalAlign": "middle",
      "scrollBarMargin": 2
     },
     "this.IconButton_52344940_5F01_EFC4_4184_BD88B8F3E7CC",
     "this.IconButton_52344940_5F01_EFC4_41C7_7571D1A24A33",
     {
      "mode": "toggle",
      "width": 40,
      "height": 40,
      "iconURL": "skin/IconButton_52344940_5F01_EFC4_41CC_9E18548B3CCC.png",
      "minHeight": 0,
      "borderRadius": 0,
      "horizontalAlign": "center",
      "shadow": false,
      "transparencyActive": true,
      "cursor": "hand",
      "paddingRight": 0,
      "backgroundOpacity": 0,
      "class": "IconButton",
      "paddingBottom": 0,
      "pressedIconURL": "skin/IconButton_52344940_5F01_EFC4_41CC_9E18548B3CCC_pressed.png",
      "id": "IconButton_52344940_5F01_EFC4_41CC_9E18548B3CCC",
      "paddingLeft": 0,
      "borderSize": 0,
      "minWidth": 0,
      "verticalAlign": "middle",
      "paddingTop": 0
     },
     "this.IconButton_52344940_5F01_EFC4_41BB_7EDA152A8375"
    ],
    "paddingTop": 0,
    "verticalAlign": "middle",
    "scrollBarMargin": 2
   },
   "this.IconButton_C8BB337C_C487_407F_41C6_55C7E5D3FD2F"
  ],
  "paddingTop": 0,
  "scrollBarMargin": 2
 }
], 
 "scrollBarWidth": 10,
 "mouseWheelEnabled": true,
 "buttonToggleMute": "this.IconButton_52344940_5F01_EFC4_41CC_9E18548B3CCC",
 "start": "this.visibleComponentsIfPlayerFlagEnabled([this.IconButton_C8BB337C_C487_407F_41C6_55C7E5D3FD2F], 'cardboardAvailable'); this.mainPlayList.set('selectedIndex', 0)",
 "vrPolyfillScale": 0.5,
 "height": "100%",
 "width": "100%",
 "minHeight": 20,
 "borderRadius": 0,
 "gap": 10,
 "backgroundPreloadEnabled": true,
 "scripts": {
  "showPopupImage": function(image, toggleImage, customWidth, customHeight, showEffect, hideEffect, closeButtonProperties, autoCloseMilliSeconds, audio, stopBackgroundAudio, loadedCallback, hideCallback){  var self = this; var closed = false; var playerClickFunction = function() { zoomImage.unbind('loaded', loadedFunction, self); hideFunction(); }; var clearAutoClose = function(){ zoomImage.unbind('click', clearAutoClose, this); if(timeoutID != undefined){ clearTimeout(timeoutID); } }; var loadedFunction = function(){ self.unbind('click', playerClickFunction, self); veil.set('visible', true); setCloseButtonPosition(); closeButton.set('visible', true); zoomImage.unbind('loaded', loadedFunction, this); zoomImage.bind('userInteractionStart', userInteractionStartFunction, this); zoomImage.bind('userInteractionEnd', userInteractionEndFunction, this); timeoutID = setTimeout(timeoutFunction, 200); }; var timeoutFunction = function(){ timeoutID = undefined; if(autoCloseMilliSeconds){ var autoCloseFunction = function(){ hideFunction(); }; zoomImage.bind('click', clearAutoClose, this); timeoutID = setTimeout(autoCloseFunction, autoCloseMilliSeconds); } zoomImage.bind('backgroundClick', hideFunction, this); if(toggleImage) { zoomImage.bind('click', toggleFunction, this); zoomImage.set('imageCursor', 'hand'); } closeButton.bind('click', hideFunction, this); if(loadedCallback) loadedCallback(); }; var hideFunction = function() { self.MainViewer.set('toolTipEnabled', true); closed = true; if(timeoutID) clearTimeout(timeoutID); if(autoCloseMilliSeconds) clearAutoClose(); if(hideCallback) hideCallback(); zoomImage.set('visible', false); if(hideEffect && hideEffect.get('duration') > 0){ hideEffect.bind('end', endEffectFunction, this); } else{ zoomImage.set('image', null); } closeButton.set('visible', false); veil.set('visible', false); self.unbind('click', playerClickFunction, self); zoomImage.unbind('backgroundClick', hideFunction, this); zoomImage.unbind('userInteractionStart', userInteractionStartFunction, this); zoomImage.unbind('userInteractionEnd', userInteractionEndFunction, this, true); if(toggleImage) { zoomImage.unbind('click', toggleFunction, this); zoomImage.set('cursor', 'default'); } closeButton.unbind('click', hideFunction, this); self.resumePlayers(playersPaused, audio == null || stopBackgroundAudio); if(audio){ if(stopBackgroundAudio){ self.resumeGlobalAudios(); } self.stopGlobalAudio(audio); } }; var endEffectFunction = function() { zoomImage.set('image', null); hideEffect.unbind('end', endEffectFunction, this); }; var toggleFunction = function() { zoomImage.set('image', isToggleVisible() ? image : toggleImage); }; var isToggleVisible = function() { return zoomImage.get('image') == toggleImage; }; var setCloseButtonPosition = function() { var right = zoomImage.get('actualWidth') - zoomImage.get('imageLeft') - zoomImage.get('imageWidth') + 10; var top = zoomImage.get('imageTop') + 10; if(right < 10) right = 10; if(top < 10) top = 10; closeButton.set('right', right); closeButton.set('top', top); }; var userInteractionStartFunction = function() { if(timeoutUserInteractionID){ clearTimeout(timeoutUserInteractionID); timeoutUserInteractionID = undefined; } else{ closeButton.set('visible', false); } }; var userInteractionEndFunction = function() { if(!closed){ timeoutUserInteractionID = setTimeout(userInteractionTimeoutFunction, 300); } }; var userInteractionTimeoutFunction = function() { timeoutUserInteractionID = undefined; closeButton.set('visible', true); setCloseButtonPosition(); }; this.MainViewer.set('toolTipEnabled', false); var veil = this.veilPopupPanorama; var zoomImage = this.zoomImagePopupPanorama; var closeButton = this.closeButtonPopupPanorama; if(closeButtonProperties){ for(var key in closeButtonProperties){ closeButton.set(key, closeButtonProperties[key]); } } var playersPaused = this.pauseCurrentPlayers(audio == null || !stopBackgroundAudio); if(audio){ if(stopBackgroundAudio){ this.pauseGlobalAudios(); } this.playGlobalAudio(audio); } var timeoutID = undefined; var timeoutUserInteractionID = undefined; zoomImage.bind('loaded', loadedFunction, this); setTimeout(function(){ self.bind('click', playerClickFunction, self, false); }, 0); zoomImage.set('image', image); zoomImage.set('customWidth', customWidth); zoomImage.set('customHeight', customHeight); zoomImage.set('showEffect', showEffect); zoomImage.set('hideEffect', hideEffect); zoomImage.set('visible', true); return zoomImage; },
  "autotriggerAtStart": function(player, callback){  var stateChangeFunction = function(event){ if(event.data.state == 'playing'){ callback(); player.unbind('stateChange', stateChangeFunction, this); } }; player.bind('stateChange', stateChangeFunction, this); },
  "unregisterKey": function(key){  delete window[key]; },
  "fixTogglePlayPauseButton": function(player){  var state = player.get('state'); var button = player.get('buttonPlayPause'); if(typeof button !== 'undefined' && player.get('state') == 'playing'){ button.set('pressed', true); } },
  "changeBackgroundWhilePlay": function(playList, index, color){  var changeFunction = function(event){ if(event.data.previousSelectedIndex == index){ playList.unbind('change', changeFunction, this); if((color == viewerArea.get('backgroundColor')) && (colorRatios == viewerArea.get('backgroundColorRatios'))){ viewerArea.set('backgroundColor', backgroundColorBackup); viewerArea.set('backgroundColorRatios', backgroundColorRatiosBackup); } } }; var playListItem = playList.get('items')[index]; var player = playListItem.get('player'); var viewerArea = player.get('viewerArea'); var backgroundColorBackup = viewerArea.get('backgroundColor'); var backgroundColorRatiosBackup = viewerArea.get('backgroundColorRatios'); var colorRatios = [0]; if((color != backgroundColorBackup) || (colorRatios != backgroundColorRatiosBackup)){ viewerArea.set('backgroundColor', color); viewerArea.set('backgroundColorRatios', colorRatios); playList.bind('change', changeFunction, this); } },
  "pauseCurrentPlayers": function(onlyPauseCameraIfPanorama){  var players = this.getCurrentPlayers(); var i = players.length; while(i-- > 0){ var player = players[i]; if(player.get('state') == 'playing') { if(onlyPauseCameraIfPanorama && player.get('class') == 'PanoramaPlayer' && typeof player.get('video') === 'undefined'){ player.pauseCamera(); } else if(player.get('state') == 'playing') { player.pause(); } } else { players.splice(i, 1); } } return players; },
  "setMainMediaByIndex": function(index){  if(index >= 0 && index < this.mainPlayList.get('items').length){ this.mainPlayList.set('selectedIndex', index); } },
  "executeFunctionWhenChange": function(playList, index, endFunction, changeFunction){  var self = this; var endObject = undefined; var changePlayListFunction = function(event){ if(event.data.previousSelectedIndex == index){ if(changeFunction) changeFunction(); if(endFunction && endObject) endObject.unbind('end', endFunction, self); playList.unbind('change', changePlayListFunction, self); } }; if(endFunction){ var playListItem = playList.get('items')[index]; var playListItemClass = playListItem.get('class'); if(playListItemClass == 'PanoramaPlayListItem'){ var camera = playListItem.get('camera'); endObject = camera.get('initialSequence'); } else{ endObject = playListItem.get('media'); } if(endObject){ endObject.bind('end', endFunction, this); } } playList.bind('change', changePlayListFunction, this); },
  "pauseGlobalAudiosWhilePlayItem": function(playList, index, caller){  var audios = window.currentGlobalAudios; if(!audios) return; var resumeFunction = this.resumeGlobalAudios; var endFunction = function(){ if(playList.get('selectedIndex') != index) { resumeFunction(caller); } }; this.pauseGlobalAudios(caller); this.executeFunctionWhenChange(playList, index, endFunction, endFunction); },
  "setMainMediaByName": function(name){  var items = this.mainPlayList.get('items'); for(var i = 0; i<items.length; ++i){ if(items[i].get('media').get('label') == name) { this.mainPlayList.set('selectedIndex', i); return; } } },
  "showPopupMedia": function(w, media, playList, popupMaxWidth, popupMaxHeight, autoCloseWhenFinished, containsAudio){  var self = this; var closeFunction = function(){ self.MainViewer.set('toolTipEnabled', true); this.resumePlayers(playersPaused, !containsAudio); if(isVideo) { this.unbind('resize', resizeFunction, this); } w.unbind('close', closeFunction, this); }; var endFunction = function(){ w.hide(); }; var resizeFunction = function(){ var parentWidth = self.get('actualWidth'); var parentHeight = self.get('actualHeight'); var mediaWidth = media.get('width'); var mediaHeight = media.get('height'); var popupMaxWidthNumber = parseFloat(popupMaxWidth) / 100; var popupMaxHeightNumber = parseFloat(popupMaxHeight) / 100; var windowWidth = popupMaxWidthNumber * parentWidth; var windowHeight = popupMaxHeightNumber * parentHeight; var footerHeight = w.get('footerHeight'); var headerHeight = w.get('headerHeight'); if(!headerHeight) { var closeButtonHeight = w.get('closeButtonIconHeight') + w.get('closeButtonPaddingTop') + w.get('closeButtonPaddingBottom'); var titleHeight = w.get('titleFontSize') + w.get('titlePaddingTop') + w.get('titlePaddingBottom'); headerHeight = closeButtonHeight > titleHeight ? closeButtonHeight : titleHeight; headerHeight += w.get('headerPaddingTop') + w.get('headerPaddingBottom'); } if(!footerHeight) { footerHeight = 0; } var contentWindowWidth = windowWidth - w.get('bodyPaddingLeft') - w.get('bodyPaddingRight') - w.get('paddingLeft') - w.get('paddingRight'); var contentWindowHeight = windowHeight - headerHeight - footerHeight - w.get('bodyPaddingTop') - w.get('bodyPaddingBottom') - w.get('paddingTop') - w.get('paddingBottom'); var parentAspectRatio = contentWindowWidth / contentWindowHeight; var mediaAspectRatio = mediaWidth / mediaHeight; if(parentAspectRatio > mediaAspectRatio) { windowWidth = contentWindowHeight * mediaAspectRatio + w.get('bodyPaddingLeft') + w.get('bodyPaddingRight') + w.get('paddingLeft') + w.get('paddingRight'); } else { windowHeight = contentWindowWidth / mediaAspectRatio + headerHeight + footerHeight + w.get('bodyPaddingTop') + w.get('bodyPaddingBottom') + w.get('paddingTop') + w.get('paddingBottom'); } if(windowWidth > parentWidth * popupMaxWidthNumber) { windowWidth = parentWidth * popupMaxWidthNumber; } if(windowHeight > parentHeight * popupMaxHeightNumber) { windowHeight = parentHeight * popupMaxHeightNumber; } w.set('width', windowWidth); w.set('height', windowHeight); w.set('x', (parentWidth - w.get('actualWidth')) * 0.5); w.set('y', (parentHeight - w.get('actualHeight')) * 0.5); }; if(autoCloseWhenFinished){ this.executeFunctionWhenChange(playList, 0, endFunction); } var isVideo = media.get('class') == 'Video'; if(isVideo){ this.bind('resize', resizeFunction, this); resizeFunction(); } else { w.set('width', popupMaxWidth); w.set('height', popupMaxHeight); } this.MainViewer.set('toolTipEnabled', false); var playersPaused = this.pauseCurrentPlayers(!containsAudio); w.bind('close', closeFunction, this); w.show(this, true); },
  "existsKey": function(key){  return key in window; },
  "showWindow": function(w, autoCloseMilliSeconds, containsAudio){  if(w.get('visible') == true){ return; } var closeFunction = function(){ clearAutoClose(); this.resumePlayers(playersPaused, !containsAudio); w.unbind('close', closeFunction, this); }; var clearAutoClose = function(){ w.unbind('click', clearAutoClose, this); if(timeoutID != undefined){ clearTimeout(timeoutID); } }; var timeoutID = undefined; if(autoCloseMilliSeconds){ var autoCloseFunction = function(){ w.hide(); }; w.bind('click', clearAutoClose, this); timeoutID = setTimeout(autoCloseFunction, autoCloseMilliSeconds); } var playersPaused = this.pauseCurrentPlayers(!containsAudio); w.bind('close', closeFunction, this); w.show(this, true); },
  "pauseGlobalAudio": function(audio){  var audios = window.currentGlobalAudios; if(audios){ audio = audios[audio.get('id')]; } if(audio.get('state') == 'playing') audio.pause(); },
  "setMediaBehaviour": function(playList, index, mediaDispatcher){  var self = this; var stateChangeFunction = function(event){ if(event.data.state == 'stopped'){ dispose(true); } }; var changeFunction = function(){ var index = playListDispatcher.get('selectedIndex'); if(index != -1){ indexDispatcher = index; dispose(false); } }; var disposeCallback = function(){ dispose(false); }; var dispose = function(forceDispose){ if(!playListDispatcher) return; var media = item.get('media'); if((media.get('class') == 'Video360' || media.get('class') == 'Video') && media.get('loop') == true && !forceDispose) return; playList.set('selectedIndex', -1); if(panoramaSequence && panoramaSequenceIndex != -1){ if(panoramaSequence) { if(panoramaSequenceIndex > 0 && panoramaSequence.get('movements')[panoramaSequenceIndex-1].get('class') == 'TargetPanoramaCameraMovement'){ var initialPosition = camera.get('initialPosition'); var oldYaw = initialPosition.get('yaw'); var oldPitch = initialPosition.get('pitch'); var oldHfov = initialPosition.get('hfov'); var previousMovement = panoramaSequence.get('movements')[panoramaSequenceIndex-1]; initialPosition.set('yaw', previousMovement.get('targetYaw')); initialPosition.set('pitch', previousMovement.get('targetPitch')); initialPosition.set('hfov', previousMovement.get('targetHfov')); var restoreInitialPositionFunction = function(event){ initialPosition.set('yaw', oldYaw); initialPosition.set('pitch', oldPitch); initialPosition.set('hfov', oldHfov); itemDispatcher.unbind('end', restoreInitialPositionFunction, self); }; itemDispatcher.bind('end', restoreInitialPositionFunction, self); } panoramaSequence.set('movementIndex', panoramaSequenceIndex); } } playListDispatcher.set('selectedIndex', indexDispatcher); if(player){ player.unbind('stateChange', stateChangeFunction, self); for(var i = 0; i<buttons.length; ++i) { buttons[i].unbind('click', disposeCallback, self); } } if(sameViewerArea){ if(playList != playListDispatcher) playListDispatcher.unbind('change', changeFunction, self); } else{ viewerArea.set('visible', false); } playListDispatcher = undefined; }; var mediaDispatcherByParam = mediaDispatcher != undefined; if(!mediaDispatcher){ var currentIndex = playList.get('selectedIndex'); var currentPlayer = (currentIndex != -1) ? playList.get('items')[playList.get('selectedIndex')].get('player') : this.getActivePlayerWithViewer(this.MainViewer); if(currentPlayer) { var playerClass = currentPlayer.get('class'); if(playerClass == 'PanoramaPlayer') { mediaDispatcher = currentPlayer.get('panorama'); if(mediaDispatcher == undefined) medisDispatcher = currentPlayer.get('video'); } else if(playerClass == 'VideoPlayer' || playerClass == 'Video360Player') mediaDispatcher = currentPlayer.get('video'); else if(playerClass == 'PhotoAlbumPlayer') mediaDispatcher = currentPlayer.get('photoAlbum'); else if(playerClass == 'MapPlayer') mediaDispatcher = currentPlayer.get('map'); } } var playListDispatcher = mediaDispatcher ? this.getPlayListWithMedia(mediaDispatcher, true) : undefined; if(!playListDispatcher){ playList.set('selectedIndex', index); return; } var indexDispatcher = playListDispatcher.get('selectedIndex'); if(playList.get('selectedIndex') == index || indexDispatcher == -1){ return; } var item = playList.get('items')[index]; var itemDispatcher = playListDispatcher.get('items')[indexDispatcher]; var viewerArea = item.get('player').get('viewerArea'); var sameViewerArea = viewerArea == itemDispatcher.get('player').get('viewerArea'); if(sameViewerArea){ if(playList != playListDispatcher){ playListDispatcher.set('selectedIndex', -1); playListDispatcher.bind('change', changeFunction, this); } } else{ viewerArea.set('visible', true); } var panoramaSequenceIndex = -1; var panoramaSequence = undefined; var camera = itemDispatcher.get('camera'); if(camera){ panoramaSequence = camera.get('initialSequence'); if(panoramaSequence) { panoramaSequenceIndex = panoramaSequence.get('movementIndex'); } } playList.set('selectedIndex', index); var player = undefined; var buttons = []; if(item.get('player') != itemDispatcher.get('player') || !mediaDispatcherByParam){ player = item.get('player'); if(player.get('class') == 'PanoramaPlayer' && item.get('media').get('class') != 'Video360') { var addButtons = function(property){ var value = player.get(property); if(Array.isArray(value)) buttons = buttons.concat(value); else buttons.push(value); }; addButtons('buttonStop'); for(var i = 0; i<buttons.length; ++i) { buttons[i].bind('click', disposeCallback, this); } } else { setTimeout(function(){player.bind('stateChange', stateChangeFunction, self)}, 100); } } this.executeFunctionWhenChange(playList, index, disposeCallback); },
  "getKey": function(key){  return window[key]; },
  "openLink": function(url, name){  if(url == location.href) { return; } if (name == '_blank' && window && window.process && window.process.versions && window.process.versions['electron']){ if (url.startsWith('/')) { var r = window.location.href.split('/'); r.pop(); url = r.join('/') + url; } var extension = url.split('.').pop().toLowerCase(); if(extension != 'pdf') { var shell = require('electron').shell; shell.openExternal(url); } else { window.open(url, name); } } else { var newWindow = window.open(url, name); newWindow.focus(); } },
  "getActivePlayerWithViewer": function(viewerArea){  var players = this.getByClassName('PanoramaPlayer'); players = players.concat(this.getByClassName('VideoPlayer')); players = players.concat(this.getByClassName('Video360Player')); players = players.concat(this.getByClassName('PhotoAlbumPlayer')); players = players.concat(this.getByClassName('MapPlayer')); var i = players.length; while(i-- > 0){ var player = players[i]; if(player.get('viewerArea') == viewerArea) { var playerClass = player.get('class'); if(playerClass == 'PanoramaPlayer' && (player.get('panorama') != undefined || player.get('video') != undefined)) return player; else if((playerClass == 'VideoPlayer' || playerClass == 'Video360Player') && player.get('video') != undefined) return player; else if(playerClass == 'PhotoAlbumPlayer' && player.get('photoAlbum') != undefined) return player; else if(playerClass == 'MapPlayer' && player.get('map') != undefined) return player; } } return undefined; },
  "pauseGlobalAudios": function(caller){  var audios = window.currentGlobalAudios; window.currentGlobalAudiosActionCaller = caller; if(!audios) return; for(var audio in audios){ var a = audios[audio]; if(a.get('state') == 'playing') a.pause(); } },
  "setStartTimeVideo": function(media, time){  var items = this.getPlayListItems(media); var startTimeBackup = []; var restoreStartTimeFunc = function() { for(var i = 0; i<items.length; ++i){ var item = items[i]; item.set('startTime', startTimeBackup[i]); item.unbind('stop', restoreStartTimeFunc, this); } }; for(var i = 0; i<items.length; ++i) { var item = items[i]; startTimeBackup.push(item.get('startTime')); item.set('startTime', time); item.bind('stop', restoreStartTimeFunc, this); } },
  "registerKey": function(key, value){  window[key] = value; },
  "getCurrentPlayerWithMedia": function(media){  var playerClass = undefined; var mediaPropertyName = undefined; switch(media.get('class')) { case 'Panorama': case 'LivePanorama': case 'HDRPanorama': playerClass = 'PanoramaPlayer'; mediaPropertyName = 'panorama'; break; case 'Video360': playerClass = 'PanoramaPlayer'; mediaPropertyName = 'video'; break; case 'PhotoAlbum': playerClass = 'PhotoAlbumPlayer'; mediaPropertyName = 'photoAlbum'; break; case 'Map': playerClass = 'MapPlayer'; mediaPropertyName = 'map'; break; case 'Video': playerClass = 'VideoPlayer'; mediaPropertyName = 'video'; break; }; if(playerClass != undefined) { var players = this.getByClassName(playerClass); for(var i = 0; i<players.length; ++i){ var player = players[i]; if(player.get(mediaPropertyName) == media) { return player; } } } else { return undefined; } },
  "playAudioList": function(audios){  if(audios.length == 0) return; var currentAudioCount = -1; var currentAudio; var playGlobalAudioFunction = this.playGlobalAudio; var playNext = function(){ if(++currentAudioCount >= audios.length) currentAudioCount = 0; currentAudio = audios[currentAudioCount]; playGlobalAudioFunction(currentAudio, playNext); }; playNext(); },
  "setStartTimeVideoSync": function(media, player){  this.setStartTimeVideo(media, player.get('currentTime')); },
  "showPopupPanoramaVideoOverlay": function(popupPanoramaOverlay, closeButtonProperties){  var self = this; var showEndFunction = function() { popupPanoramaOverlay.unbind('showEnd', showEndFunction); closeButton.bind('click', hideFunction, this); setCloseButtonPosition(); closeButton.set('visible', true); }; var endFunction = function() { if(!popupPanoramaOverlay.get('loop')) hideFunction(); }; var hideFunction = function() { self.MainViewer.set('toolTipEnabled', true); popupPanoramaOverlay.set('visible', false); closeButton.set('visible', false); closeButton.unbind('click', hideFunction, self); popupPanoramaOverlay.unbind('end', endFunction, self); popupPanoramaOverlay.unbind('hideEnd', hideFunction, self, true); self.resumePlayers(playersPaused, true); self.resumeGlobalAudios(); }; var setCloseButtonPosition = function() { var right = 10; var top = 10; closeButton.set('right', right); closeButton.set('top', top); }; this.MainViewer.set('toolTipEnabled', false); var closeButton = this.closeButtonPopupPanorama; if(closeButtonProperties){ for(var key in closeButtonProperties){ closeButton.set(key, closeButtonProperties[key]); } } var playersPaused = this.pauseCurrentPlayers(true); this.pauseGlobalAudios(); popupPanoramaOverlay.bind('end', endFunction, this, true); popupPanoramaOverlay.bind('showEnd', showEndFunction, this, true); popupPanoramaOverlay.bind('hideEnd', hideFunction, this, true); popupPanoramaOverlay.set('visible', true); },
  "getCurrentPlayers": function(){  var players = this.getByClassName('PanoramaPlayer'); players = players.concat(this.getByClassName('VideoPlayer')); players = players.concat(this.getByClassName('Video360Player')); players = players.concat(this.getByClassName('PhotoAlbumPlayer')); return players; },
  "playGlobalAudioWhilePlay": function(playList, index, audio, endCallback){  var changeFunction = function(event){ if(event.data.previousSelectedIndex == index){ this.stopGlobalAudio(audio); if(isPanorama) { var media = playListItem.get('media'); var audios = media.get('audios'); audios.splice(audios.indexOf(audio), 1); media.set('audios', audios); } playList.unbind('change', changeFunction, this); if(endCallback) endCallback(); } }; var audios = window.currentGlobalAudios; if(audios && audio.get('id') in audios){ audio = audios[audio.get('id')]; if(audio.get('state') != 'playing'){ audio.play(); } return; } playList.bind('change', changeFunction, this); var playListItem = playList.get('items')[index]; var isPanorama = playListItem.get('class') == 'PanoramaPlayListItem'; if(isPanorama) { var media = playListItem.get('media'); var audios = (media.get('audios') || []).slice(); if(audio.get('class') == 'MediaAudio') { var panoramaAudio = this.rootPlayer.createInstance('PanoramaAudio'); panoramaAudio.set('autoplay', false); panoramaAudio.set('audio', audio.get('audio')); panoramaAudio.set('loop', audio.get('loop')); panoramaAudio.set('id', audio.get('id')); audio = panoramaAudio; } audios.push(audio); media.set('audios', audios); } this.playGlobalAudio(audio, endCallback); },
  "shareFacebook": function(url){  window.open('https://www.facebook.com/sharer/sharer.php?u=' + url, '_blank'); },
  "startPanoramaWithCamera": function(panorama, camera){  var playLists = this.getByClassName('PlayList'); if(playLists.length == 0) return; var restoreItems = []; for(var i = 0, count = playLists.length; i<count; ++i){ var playList = playLists[i]; var items = playList.get('items'); for(var j = 0, countJ = items.length; j<countJ; ++j){ var item = items[j]; if(item.get('media') == panorama && item.get('class') == 'PanoramaPlayListItem'){ restoreItems.push({camera: item.get('camera'), item: item}); item.set('camera', camera); } } } if(restoreItems.length > 0) { var restoreCameraOnStop = function(){ for (var i = 0; i < restoreItems.length; i++) { restoreItems[i].item.set('camera', restoreItems[i].camera); } restoreItems[0].item.unbind('stop', restoreCameraOnStop, this); }; restoreItems[0].item.bind('stop', restoreCameraOnStop, this); } },
  "setMapLocation": function(panoramaPlayListItem, mapPlayer){  var resetFunction = function(){ panoramaPlayListItem.unbind('stop', resetFunction, this); player.set('mapPlayer', null); }; panoramaPlayListItem.bind('stop', resetFunction, this); var player = panoramaPlayListItem.get('player'); player.set('mapPlayer', mapPlayer); },
  "getGlobalAudio": function(audio){  var audios = window.currentGlobalAudios; if(audios != undefined && audio.get('id') in audios){ audio = audios[audio.get('id')]; } return audio; },
  "playGlobalAudio": function(audio, endCallback){  var endFunction = function(){ audio.unbind('end', endFunction, this); this.stopGlobalAudio(audio); if(endCallback) endCallback(); }; audio = this.getGlobalAudio(audio); var audios = window.currentGlobalAudios; if(!audios){ audios = window.currentGlobalAudios = {}; } audios[audio.get('id')] = audio; if(audio.get('state') == 'playing'){ return; } if(!audio.get('loop')){ audio.bind('end', endFunction, this); } audio.play(); },
  "shareGoogle": function(url){  window.open('https://plus.google.com/share?url=' + url, '_blank'); },
  "getPlayListWithMedia": function(media, onlySelected){  var playLists = this.getByClassName('PlayList'); for(var i = 0, count = playLists.length; i<count; ++i){ var playList = playLists[i]; if(onlySelected && playList.get('selectedIndex') == -1) continue; var items = playList.get('items'); for(var j = 0, countJ = items.length; j<countJ; ++j){ if(items[j].get('media') == media) return playList; } } return undefined; },
  "syncPlaylists": function(playLists){  var changeToMedia = function(media, playListDispatched){ for(var i = 0, count = playLists.length; i<count; ++i){ var playList = playLists[i]; if(playList != playListDispatched){ var items = playList.get('items'); for(var j = 0, countJ = items.length; j<countJ; ++j){ if(items[j].get('media') == media){ if(playList.get('selectedIndex') != j){ playList.set('selectedIndex', j); } break; } } } } }; var changeFunction = function(event){ var playListDispatched = event.source; var selectedIndex = playListDispatched.get('selectedIndex'); if(selectedIndex < 0) return; var media = playListDispatched.get('items')[selectedIndex].get('media'); changeToMedia(media, playListDispatched); }; var mapPlayerChangeFunction = function(event){ var panoramaMapLocation = event.source.get('panoramaMapLocation'); if(panoramaMapLocation){ var map = panoramaMapLocation.get('map'); changeToMedia(map); } }; for(var i = 0, count = playLists.length; i<count; ++i){ playLists[i].bind('change', changeFunction, this); } var mapPlayers = this.getByClassName('MapPlayer'); for(var i = 0, count = mapPlayers.length; i<count; ++i){ mapPlayers[i].bind('panoramaMapLocation_change', mapPlayerChangeFunction, this); } },
  "resumePlayers": function(players, onlyResumeCameraIfPanorama){  for(var i = 0; i<players.length; ++i){ var player = players[i]; if(onlyResumeCameraIfPanorama && player.get('class') == 'PanoramaPlayer' && typeof player.get('video') === 'undefined'){ player.resumeCamera(); } else{ player.play(); } } },
  "shareTwitter": function(url){  window.open('https://twitter.com/intent/tweet?source=webclient&url=' + url, '_blank'); },
  "updateMediaLabelFromPlayList": function(playList, htmlText, playListItemStopToDispose){  var changeFunction = function(){ var index = playList.get('selectedIndex'); if(index >= 0){ var beginFunction = function(){ playListItem.unbind('begin', beginFunction); setMediaLabel(index); }; var setMediaLabel = function(index){ var media = playListItem.get('media'); var text = media.get('data'); if(!text) text = media.get('label'); setHtml(text); }; var setHtml = function(text){ if(text !== undefined) { htmlText.set('visible', true); htmlText.set('html', '<div style=\"text-align:left\"><SPAN STYLE=\"color:#FFFFFF;font-size:12px;font-family:Verdana\"><span color=\"white\" font-family=\"Verdana\" font-size=\"12px\">' + text + '</SPAN></div>'); } else { htmlText.set('visible', false); htmlText.set('html', ''); } }; var playListItem = playList.get('items')[index]; if(htmlText.get('html')){ setHtml('Loading...'); playListItem.bind('begin', beginFunction); } else{ setMediaLabel(index); } } }; var disposeFunction = function(){ htmlText.set('html', undefined); playList.unbind('change', changeFunction, this); playListItemStopToDispose.unbind('stop', disposeFunction, this); }; if(playListItemStopToDispose){ playListItemStopToDispose.bind('stop', disposeFunction, this); } playList.bind('change', changeFunction, this); changeFunction(); },
  "getPlayListItems": function(media, player){  var itemClass = (function() { switch(media.get('class')) { case 'Panorama': case 'LivePanorama': case 'HDRPanorama': return 'PanoramaPlayListItem'; case 'Video360': return 'Video360PlayListItem'; case 'PhotoAlbum': return 'PhotoAlbumPlayListItem'; case 'Map': return 'MapPlayListItem'; case 'Video': return 'VideoPlayListItem'; } })(); if (itemClass != undefined) { var items = this.getByClassName(itemClass); for (var i = items.length-1; i>=0; --i) { var item = items[i]; if(item.get('media') != media || (player != undefined && item.get('player') != player)) { items.splice(i, 1); } } return items; } else { return []; } },
  "resumeGlobalAudios": function(caller){  if(window.currentGlobalAudiosActionCaller && window.currentGlobalAudiosActionCaller != caller) return; window.currentGlobalAudiosActionCaller = undefined; var audios = window.currentGlobalAudios; if(!audios) return; for(var audio in audios){ audios[audio].play(); } },
  "showComponentsWhileMouseOver": function(parentComponent, components, durationVisibleWhileOut){  var setVisibility = function(visible){ for(var i = 0, length = components.length; i<length; i++){ var component = components[i]; if(component.get('class') == 'HTMLText' && (component.get('text') == '' || component.get('text') == undefined)) { continue; } component.set('visible', visible); } }; if (this.rootPlayer.get('touchEnabled') == true){ setVisibility(true); } else { var timeoutID = -1; var rollOverFunction = function(){ setVisibility(true); if(timeoutID >= 0) clearTimeout(timeoutID); parentComponent.unbind('rollOver', rollOverFunction, this); parentComponent.bind('rollOut', rollOutFunction, this); }; var rollOutFunction = function(){ var timeoutFunction = function(){ setVisibility(false); parentComponent.unbind('rollOver', rollOverFunction, this); }; parentComponent.unbind('rollOut', rollOutFunction, this); parentComponent.bind('rollOver', rollOverFunction, this); timeoutID = setTimeout(timeoutFunction, durationVisibleWhileOut); }; parentComponent.bind('rollOver', rollOverFunction, this); } },
  "isCardboardViewMode": function(){  var players = this.getByClassName('PanoramaPlayer'); return players.length > 0 && players[0].get('viewMode') == 'cardboard'; },
  "stopGlobalAudio": function(audio){  var audios = window.currentGlobalAudios; if(audios){ audio = audios[audio.get('id')]; if(audio) delete audios[audio.get('id')]; } if(audio) audio.stop(); },
  "updateVideoCues": function(playList, index){  var playListItem = playList.get('items')[index]; var video = playListItem.get('media'); if(video.get('cues').length == 0) return; var player = playListItem.get('player'); var cues = []; var changeFunction = function(){ if(playList.get('selectedIndex') != index){ video.unbind('cueChange', cueChangeFunction, this); playList.unbind('change', changeFunction, this); } }; var cueChangeFunction = function(event){ var activeCues = event.data.activeCues; for(var i = 0, count = cues.length; i<count; ++i){ var cue = cues[i]; if(activeCues.indexOf(cue) == -1 && (cue.get('startTime') > player.get('currentTime') || cue.get('endTime') < player.get('currentTime')+0.5)){ cue.trigger('end'); } } cues = activeCues; }; video.bind('cueChange', cueChangeFunction, this); playList.bind('change', changeFunction, this); },
  "loopAlbum": function(playList, index){  var playListItem = playList.get('items')[index]; var player = playListItem.get('player'); var loopFunction = function(){ player.play(); }; this.executeFunctionWhenChange(playList, index, loopFunction); },
  "setComponentVisibility": function(component, visible, applyAt, effect, propertyEffect, ignoreClearTimeout){  this.unregisterKey('visibility_'+component.get('id')); var changeVisibility = function(){ if(effect && propertyEffect){ component.set(propertyEffect, effect); } component.set('visible', visible); if(component.get('class') == 'ViewerArea'){ try{ if(visible) component.restart(); else if(component.get('playbackState') == 'playing') component.pause(); } catch(e){}; } }; var effectTimeoutName = 'effectTimeout_'+component.get('id'); if(!ignoreClearTimeout && window.hasOwnProperty(effectTimeoutName)){ var effectTimeout = window[effectTimeoutName]; if(effectTimeout instanceof Array){ for(var i=0; i<effectTimeout.length; i++){ clearTimeout(effectTimeout[i]) } }else{ clearTimeout(effectTimeout); } delete window[effectTimeoutName]; } else if(visible == component.get('visible') && !ignoreClearTimeout) return; if(applyAt && applyAt > 0){ var effectTimeout = setTimeout(function(){ if(window[effectTimeoutName] instanceof Array) { var arrayTimeoutVal = window[effectTimeoutName]; var index = arrayTimeoutVal.indexOf(effectTimeout); arrayTimeoutVal.splice(index, 1); if(arrayTimeoutVal.length == 0){ delete window[effectTimeoutName]; } }else{ delete window[effectTimeoutName]; } changeVisibility(); }, applyAt); if(window.hasOwnProperty(effectTimeoutName)){ window[effectTimeoutName] = [window[effectTimeoutName], effectTimeout]; }else{ window[effectTimeoutName] = effectTimeout; } } else{ changeVisibility(); } },
  "visibleComponentsIfPlayerFlagEnabled": function(components, playerFlag){  var enabled = this.get(playerFlag); for(var i in components){ components[i].set('visible', enabled); } },
  "loadFromCurrentMediaPlayList": function(playList, delta){  var currentIndex = playList.get('selectedIndex'); var totalItems = playList.get('items').length; var newIndex = (currentIndex + delta) % totalItems; while(newIndex < 0){ newIndex = totalItems + newIndex; }; if(currentIndex != newIndex){ playList.set('selectedIndex', newIndex); }; },
  "setEndToItemIndex": function(playList, fromIndex, toIndex){  var endFunction = function(){ if(playList.get('selectedIndex') == fromIndex) playList.set('selectedIndex', toIndex); }; this.executeFunctionWhenChange(playList, fromIndex, endFunction); }
 },
 "horizontalAlign": "left",
 "shadow": false,
 "layout": "absolute",
 "contentOpaque": false,
 "scrollBarColor": "#000000",
 "paddingBottom": 0,
 "paddingRight": 0,
 "class": "Player",
 "paddingLeft": 0,
 "scrollBarOpacity": 0.5,
 "overflow": "visible",
 "id": "rootPlayer",
 "minWidth": 20,
 "borderSize": 0,
 "scrollBarVisible": "rollOver",
 "paddingTop": 0,
 "verticalAlign": "top",
 "scrollBarMargin": 2
})